# config.yaml
transport:
  type: streamable_http
schema:
  source: local
  path: ./schema.graphql
endpoint: https://4b94-105-235-133-201.ngrok-free.app/graphql
operations:
  source: local
  paths:
    - ./operations/
introspection:
  introspect:
    enabled: true
  search:
    enabled: true
  validate:
    enabled: true
  execute:
    enabled: true
