package ncshack.samba.mizan.ui.theme

import androidx.compose.ui.graphics.Color

// Seed color: #012C3C — dark teal, trustworthy/legal tone
val Primary = Color(0xFF012C3C)

// M3 Light Color Scheme — seeded from #012C3C
val md_theme_light_primary = Color(0xFF012C3C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA1D4E0)
val md_theme_light_onPrimaryContainer = Color(0xFF001F29)
val md_theme_light_secondary = Color(0xFF4A626C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7F1)
val md_theme_light_onSecondaryContainer = Color(0xFF051F28)
val md_theme_light_tertiary = Color(0xFF5B5C3E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE1B8)
val md_theme_light_onTertiaryContainer = Color(0xFF191C06)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FAFD)
val md_theme_light_onBackground = Color(0xFF171C1F)
val md_theme_light_surface = Color(0xFFF5FAFD)
val md_theme_light_onSurface = Color(0xFF171C1F)
val md_theme_light_surfaceVariant = Color(0xFFDDE4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71797E)
val md_theme_light_outlineVariant = Color(0xFFC1C8CD)
val md_theme_light_inverseSurface = Color(0xFF2C3133)
val md_theme_light_inverseOnSurface = Color(0xFFEDF1F4)
val md_theme_light_inversePrimary = Color(0xFF85D3E1)
val md_theme_light_surfaceTint = Color(0xFF012C3C)
val md_theme_light_scrim = Color(0xFF000000)

// M3 Dark Color Scheme — seeded from #012C3C
val md_theme_dark_primary = Color(0xFF85D3E1)
val md_theme_dark_onPrimary = Color(0xFF003647)
val md_theme_dark_primaryContainer = Color(0xFF014F63)
val md_theme_dark_onPrimaryContainer = Color(0xFFA1D4E0)
val md_theme_dark_secondary = Color(0xFFB1CBD6)
val md_theme_dark_onSecondary = Color(0xFF1C343D)
val md_theme_dark_secondaryContainer = Color(0xFF334B54)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7F1)
val md_theme_dark_tertiary = Color(0xFFC3C59D)
val md_theme_dark_onTertiary = Color(0xFF2E301A)
val md_theme_dark_tertiaryContainer = Color(0xFF45462B)
val md_theme_dark_onTertiaryContainer = Color(0xFFDFE1B8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0E1416)
val md_theme_dark_onBackground = Color(0xFFDDE4E8)
val md_theme_dark_surface = Color(0xFF0E1416)
val md_theme_dark_onSurface = Color(0xFFDDE4E8)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C8CD)
val md_theme_dark_outline = Color(0xFF8B9297)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_inverseSurface = Color(0xFFDDE4E8)
val md_theme_dark_inverseOnSurface = Color(0xFF2C3133)
val md_theme_dark_inversePrimary = Color(0xFF012C3C)
val md_theme_dark_surfaceTint = Color(0xFF85D3E1)
val md_theme_dark_scrim = Color(0xFF000000)
